<DeleteFolderConfirmation>:
    name: 'delete_folder_confirmation'
    GranuContainer:
        GranuContent:
            GranuTitle:
                text: 'Are You Sure?'
            GridLayout:
                cols: 3
                rows: 3
                spacing: 10
                row_default_height: self.height/4
                Button:
                	background_color: (.42,.42,0.42,1)
                	font_size: 25
                    text: 'No'
                    size_hint_y: None
                    height: self.font_size + 40
                    size_hint_x: 0.25
                	halign: 'center'
                	valign: 'middle'
                	markup: True
                	bold: True
                    on_release:
                        root.move_to('test_folders_screen') # Move to testing screen
                Button:
                	background_color: (.42,.42,0.42,1)
                	font_size: 25
                    text: 'Yes'
                    size_hint_y: None
                    height: self.font_size + 40
                    size_hint_x: 0.25
                	halign: 'center'
                	valign: 'middle'
                	markup: True
                	bold: True
                    on_release:
                        root.delete_folder_yes()
                        root.move_to('test_folders_screen') # Move to testing screen