<Test>
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<TestList>
    viewclass: 'Note'
    SingleSelectableRecycleBoxLayout:

<NavButton@Button>:
    font_size: 26
    halign: 'center'
    valign: 'middle'
    markup: True
    bold: True

<SaveTestDialog>:
    markup: True
    bold: True
    title: 'Select Location'
    title_align: 'center'
    title_size: '26sp'
    size_hint: (0.9, 0.9)
    BoxLayout:
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path: '/mnt/usbStick' # str(Path.home())
        BoxLayout:
            size_hint_y: None
            height: 65
            NavButton:
                text: "Cancel"
                on_release: root.cancel()
            NavButton:
                text: "Save"
                on_release: root.save(filechooser.path)

<SaveConfirmDialog>:
    size_hint: (0.55, 0.77)
    markup: True
    bold: True
    title: 'Save Tests'
    title_align: 'center'
    title_size: '26sp'
    # size_hint: (0.5, 0.7)
    BoxLayout:
        orientation: 'vertical'
        Label:
            font_size: 26
            markup: True
            bold: True
            halign: 'left'
            text: "To save tests to USB:\n      select 'Save to USB'\nTo select another save location:\n      select 'Choose Location'\nTo cancel:\n      select 'Cancel'"
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size_hint_x: 1
            height: 65
            NavButton:
                text: "Cancel"
                on_release: root.cancel()
            NavButton:
                text: "Choose\nLocation"
                on_release: root.pathSelector()
            NavButton:
                text: "Save to\nUSB"
                on_release: root.save('/mnt/usbStick')

<NoUsbDialog>:
    size_hint: (0.55, 0.77)
    markup: True
    bold: True
    title: 'No USB Detected'
    title_align: 'center'
    title_size: '26sp'
    # size_hint: (0.5, 0.7)
    BoxLayout:
        orientation: 'vertical'
        Label:
            font_size: 26
            markup: True
            bold: True
            halign: 'center'
            text: "No USB Device was detected.\nPlease try again."
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size_hint_x: 1
            height: 65
            NavButton:
                text: "Cancel"
                on_release: root.cancel()

<TestsScreen>:
	name: 'tests_screen'
    GranuContainer:
        GranuSideArea:
            id: tests_buttons
        GranuContent:
            GranuTitle:
                text: 'Tests'
            BoxLayout:
                orientation: 'horizontal'
                TestList:
                    id: tests_list
                    on_interaction:
                        root.test_buttons()
                    on_deselect_all:
                        root.default_buttons()
