<Folder>
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<FolderList>
    viewclass: 'Note'
    SingleSelectableRecycleBoxLayout:

<NavButton@Button>:
    font_size: 26
    halign: 'center'
    valign: 'middle'
    markup: True
    bold: True

<TestFoldersScreen>:
	name: 'test_folders_screen'
    GranuContainer:
        GranuSideArea:
            id: folders_buttons
        GranuContent:
            GranuTitle:
                text: 'Folders'
            BoxLayout:
                orientation: 'horizontal'
                FolderList:
                    id: folders_list
                    on_interaction:
                        root.folder_buttons()
                    on_deselect_all:
                        root.default_folders_buttons()
